# Global Forest Watch API
# Copyright (C) 2013 World Resource Institute
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

application: gfw-apis
runtime: python27
threadsafe: true
api_version: 1

inbound_services:
- mail
# - warmup

libraries:
- name: jinja2
  version: "latest"
- name: webapp2
  version: "latest"
- name: ssl
  version: "latest"
- name: pycrypto
  version: "latest"

## GAE python console:
# remote_api_shell.py -s dev.gfw-apis.appspot.com
builtins:
- remote_api: on

handlers:

- url: /assets
  static_dir: gfw/assets

## Earth Engine dep:
- url: /oauth2callback
  script: oauth2client.appengine.application

- url: /_info
  script: gfw.info.handlers

# Download handler:
- url: /analysis/(imazon|forma|modis|prodes|viirs).(shp|geojson|kml|svg|csv)
  script: download.handlers

# Analysis handler:
- url: /analysis/(imazon|forma|modis|umd|prodes|biomassloss|guyra|glad|viirs)
  script: analysis.handlers

# Monitor
- url: /monitor.*
  script: monitor.handlers

- url: /gee.*
  script: gfw.gee_tiles.api

- url: /admin.*
  script: admin.handlers
  login: admin

- url: /forest-change
  script: gfw.forestchange.api.handlers

- url: /forest-change/(forma-alerts|umd-loss-gain|imazon-alerts|quicc-alerts|nasa-active-fires|terrai-alerts|glad-alerts|prodes-loss|biomass-loss|guyra-loss|viirs-active-fires|loss-by-type).*
  script: gfw.forestchange.api.handlers

- url: /countries.*
  script: gfw.countries.api.handlers

- url: /stories.*
  script: gfw.stories.handlers

- url: /user.*
  script: gfw.user.api.handlers

- url: /feedback.*
  script: gfw.feedback.api.handlers

- url: /geostore.*
  script: gfw.geostore.api.handlers

- url: /v2/subscriptions.*
  script: gfw.v2.subscriptions.api.handlers

- url: /manage/pubsub.*
  script: gfw.admin.pubsub.api.handlers

- url: /v2/migrations.*
  script: gfw.v2.migrations.api.handlers

- url: /metadata.*
  script: gfw.metadata.handlers

- url: /urthecast.*
  script: gfw.urthecast.handler.app

- url: /email.*
  script: gfw.email.api.handlers

- url: /migrations.*
  script: gfw.migrations.api.handlers

- url: /.*
  script: gfw.urthecast.handler.app
